### ISSUE TITLE
Update domain and make standalone

### ISSUE THREAD

**Issue by agviegas** [IFCjs/docs#19]
### Description 📝

Right now the documentation is an iframe in the platform. We want to make it standalone so that we can use all docusaurus features (such as URL paths for each tutorial)

### Validations ✅

- [X] Read the [docs](https://platform.thatopen.com/documentation).
- [X] Check that there isn't [already an issue](https://github.com/IFCjs/components/issues) that requests the same feature to avoid creating a duplicate.

**Comment by ABujalance** [comment]
Fixed in #21
